In [1]:
import numpy as np
import networkx as nx

In [2]:
# 1.2 node list
dg = np.array(
    [0,1,1,0,
    1,0,1,0,
    0,0,0,0,
    1,0,0,0]).reshape(4,4)

In [3]:
dg

array([[0, 1, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0]])

In [4]:
# 1.3 edge list
e_list = np.array([1,2,1,3,2,1,2,3,4,1])
e_matrix = e_list.reshape([-1, 2])
e_matrix

array([[1, 2],
       [1, 3],
       [2, 1],
       [2, 3],
       [4, 1]])

In [5]:
# 1.4 file import
g = np.genfromtxt('../R/workdir/adj.csv', delimiter= ',')
g

array([[0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [6]:
# 1.8
edgelist= np.array([
  1,2,1,
  1,3,1,
  2,1,1,
  2,3,1,
  4,1,1]).reshape([-1,3])

g0 = nx.Graph()
for f,t,w in edgelist:
    g0.add_edge(f,t,weight = w)

In [7]:
g0.edges

EdgeView([(1, 2), (1, 3), (1, 4), (2, 3)])

In [8]:
g0.nodes

NodeView((1, 2, 3, 4))

In [9]:
g0.adj

AdjacencyView({1: {2: {'weight': 1}, 3: {'weight': 1}, 4: {'weight': 1}}, 2: {1: {'weight': 1}, 3: {'weight': 1}}, 3: {1: {'weight': 1}, 2: {'weight': 1}}, 4: {1: {'weight': 1}}})

In [16]:
g1_mx = np.array(
  [0,1,0,
  1,0,1,
  0,1,0]).reshape([3,3])
g1 = nx.from_numpy_matrix(g1_mx, create_using=nx.DiGraph)

In [17]:
g1.nodes

NodeView((0, 1, 2))

In [18]:
g1.edges

OutEdgeView([(0, 1), (1, 0), (1, 2), (2, 1)])

In [19]:
wg_mx = np.array([
  0,2,0,4,
  2,0,3,1,
  0,3,0,0,
  4,1,0,0]).reshape([4,4])
wg = nx.from_numpy_matrix(wg_mx, create_using=nx.DiGraph)

In [20]:
wg.adj

AdjacencyView({0: {1: {'weight': 2}, 3: {'weight': 4}}, 1: {0: {'weight': 2}, 2: {'weight': 3}, 3: {'weight': 1}}, 2: {1: {'weight': 3}}, 3: {0: {'weight': 4}, 1: {'weight': 1}}})